# Generated by Django 4.2.16 on 2026-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='SKU / Código interno'),
        ),
    ]
