# Generated by Django 4.2.16 on 2026-04-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_migrate_initial_stock'),
        ('inventario', '0002_alter_producto_codigo_barras_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sucursales.sucursal'),
        ),
    ]
