# Generated by Django 4.2.16 on 2026-04-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientostock_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso de Mercadería'), ('EGRESO', 'Egreso / Venta'), ('AJUSTE', 'Ajuste de Inventario'), ('INGRESO_TRANSFERENCIA', 'Ingreso por Transferencia'), ('EGRESO_TRANSFERENCIA', 'Egreso por Transferencia')], max_length=50),
        ),
    ]
