# Generated by Django 4.2.16 on 2026-04-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variantes', '0001_initial'),
        ('inventario', '0004_alter_movimientostock_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='variantes.productovariante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_variantes',
            field=models.BooleanField(default=False, verbose_name='¿Tiene variantes?'),
        ),
    ]
