# Generated by Django 4.2.16 on 2026-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_metodo_pago_ventapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventapago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta (Débito/Crédito)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
