# Generated by Django 4.2.16 on 2026-04-28 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('tipo_documento', models.CharField(choices=[('ruc', 'RUC (Perú)'), ('nit', 'NIT (Colombia)'), ('cuit', 'CUIT (Argentina)'), ('rfc', 'RFC (México)'), ('rut', 'RUT (Chile)'), ('ci', 'Cédula / CI')], default='ruc', max_length=10, verbose_name='Tipo de documento fiscal')),
                ('documento_fiscal', models.CharField(help_text='RUC, NIT, CUIT, RFC o RUT según el país.', max_length=20, unique=True, verbose_name='Documento fiscal')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('enterprise', 'Enterprise')], default='basico', max_length=20, verbose_name='Plan')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar suspende el acceso de toda la empresa.', verbose_name='Activo')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'documento_fiscal'), name='unique_tipo_documento_fiscal'),
        ),
    ]
