# Generated by Django 4.2.16 on 2026-04-30 20:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventario', '0004_alter_movimientostock_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Atributo de Producto',
                'verbose_name_plural': 'Atributos de Productos',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Si es 0, usa el del padre', max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Si es 0, usa el del padre', max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValorAtributoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='variantes.atributoproducto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('empresa', 'atributo', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='VarianteValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variantes.atributoproducto')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variantes.valoratributoproducto')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variantes.productovariante')),
            ],
            options={
                'unique_together': {('variante', 'atributo')},
            },
        ),
        migrations.AddField(
            model_name='productovariante',
            name='valores',
            field=models.ManyToManyField(through='variantes.VarianteValor', to='variantes.valoratributoproducto'),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('empresa', 'sku'), ('empresa', 'codigo_barras')},
        ),
    ]
