# Generated by Django 4.2.16 on 2026-04-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientostock_variante_producto_tiene_variantes'),
        ('variantes', '0001_initial'),
        ('sucursales', '0002_migrate_initial_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocksucursal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stocksucursal',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks_sucursales', to='variantes.productovariante'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksucursal',
            unique_together={('sucursal', 'producto', 'variante')},
        ),
    ]
