# Generated by Django 4.2.16 on 2026-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuentacorriente',
            name='referencia',
            field=models.CharField(blank=True, help_text='ID de venta u otro documento', max_length=100, null=True),
        ),
    ]
