# Generated by Django 4.2.16 on 2026-04-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientostock_variante_producto_tiene_variantes'),
        ('variantes', '0001_initial'),
        ('transferencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transferenciaitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transferenciaitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='variantes.productovariante'),
        ),
        migrations.AlterUniqueTogether(
            name='transferenciaitem',
            unique_together={('transferencia', 'producto', 'variante')},
        ),
    ]
